---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bind-configmap
data:
  named.conf: |-
{{ tpl (.Files.Get "conf/named.conf") . | indent 4 }}
  {{- range .Values.zones }}
  {{ .file }}: |-
{{- include "zonefile" . | indent 4 }}
  {{- end }}
