---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bind-configmap
data:
  named.conf: |-
{{ .Files.Get "conf/named.conf" | indent 4 }}
  cdglan-org.zone: |-
{{ .Files.Get "conf/cdglan-org.zone" | indent 4 }}
