---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: namedtcp
    - name: dns-udp
      port: {{ .Values.port }}
      protocol: UDP
      targetPort: namedudp
