apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-config-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: {{ .Values.nfs.paths.config }}
    server: {{ .Values.nfs.server }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-downloads-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: {{ .Values.nfs.paths.downloads }}
    server: {{ .Values.nfs.server }}
