---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    k8s-app: {{ .Values.name }}
    app.kubernetes.io/part-of: {{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.containerPorts.webInterface }}
    - name: dht
      protocol: TCP
      port: {{ .Values.containerPorts.inboundTraffic }}
      targetPort: {{ .Values.containerPorts.inboundTraffic }}
    - name: dht-udp
      protocol: UDP
      port: {{ .Values.containerPorts.inboundTraffic }}
      targetPort: {{ .Values.containerPorts.inboundTraffic }}
  selector:
    app: {{ .Values.name }}
