transmission:
  name: transmission
  image: linuxserver/transmission
  versionTag: "4.0.4"
  containerPorts:
    webInterface: 9091
    incomingConnection: 51413
  ingress:
    host: transmission.cdglan.org
    port: 80
    path: /
  replicas: 1

metricsExporter:
  name: transmission-exporter
  image: metalmatze/transmission-exporter
  versionTag: "master"
  containerPorts:
    metrics: 19091
  environment:
    TRANSMISSION_ADDR: https://transmission.cdglan.org
    WEB_PATH: "/metrics"
    WEB_ADDR: ":19091"

nfs:
  server: ursula.cdglan.org
  paths:
    downloads: /export/transmission/downloads
    watch: /export/transmission/watch
    config: /export/transmission/config

serviceMonitor:
  name: transmission-service-monitor
  jobLabel: transmission-service-monitor
