---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  type: NodePort
  ports:
    - name: dns-tcp
      port: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
      protocol: TCP
    - name: dns-udp
      port: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
      protocol: UDP
