name: homeassistant
image:
  name: docker.io/homeassistant/home-assistant
  tag: latest
port: 8123
host: homeassistant.example.org
ingressClassName: nginx
ingressAnnotations: {}
affinity:
  nodeLabel: skyconnect-dongle
  value: true
storage:
  name: ha-storage
  server: ha-storage.example.org
  path: /export/homeassistant
  mountPath: /config
usb:
  devicePath: /dev/ttyUSB0
  name: dongle
