apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: {{ .Values.image }}:{{ .Values.versionTag }}
        imagePullPolicy: "Always"
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.containerPorts.webInterface }}
        - containerPort: {{ .Values.containerPorts.incomingConnection }}
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - mountPath: /downloads
          name: downloads
        - mountPath: /watch
          name: watch
        - mountPath: /config
          name: config
      volumes:
      - name: downloads
        hostPath:
          path: {{ .Values.hostPaths.downloads }}
      - name: watch
        hostPath:
          path: {{ .Values.hostPaths.watch }}
      - name: config
        hostPath:
          path: {{ .Values.hostPaths.config }}
