apiVersion: v1
kind: Service
metadata:
  labels:
    app: transmission
  name: transmission
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9091
  - name: data
    port: 51413
    targetPort: 51413
  selector:
    app: transmission
