---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.transmission.name }}
  labels:
    app: {{ .Values.transmission.name }}
    k8s-app: {{ .Values.transmission.name }}
    app.kubernetes.io/part-of: {{ .Values.transmission.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.transmission.ingress.port }}
      targetPort: {{ .Values.transmission.containerPorts.webInterface }}
    - name: dht
      protocol: TCP
      port: {{ .Values.transmission.containerPorts.incomingConnection }}
      targetPort: {{ .Values.transmission.containerPorts.incomingConnection }}
    - name: dht-udp
      protocol: UDP
      port: {{ .Values.transmission.containerPorts.incomingConnection }}
      targetPort: {{ .Values.transmission.containerPorts.incomingConnection }}
  selector:
    app: {{ .Values.transmission.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metricsExporter.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "metrics"
  labels:
    app.kubernetes.io/part-of: {{ .Values.transmission.name }}
spec:
  ports:
    - name: metrics
      port: {{ .Values.metricsExporter.containerPorts.metrics }}
      targetPort: {{ .Values.metricsExporter.containerPorts.metrics }}
  selector:
    app: {{ .Values.transmission.name }}
