prometheus:
  name: prometheus-operated
  ingress:
    host: prometheus.cdglan.org
    path: /
    port: 9090
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  name: cdg-homelab-grafana
  ingress:
    host: grafana.cdglan.org
    path: /
    port: 80
