apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          volumeMounts:
            - mountPath: "{{ .Values.storage.mountPath }}"
              name: {{ .Values.storage.name }}
            - mountPath: {{ .Values.usb.devicePath }}
              name: {{ .Values.usb.name }}
          securityContext:
            privileged: true
      volumes:
        - name: {{ .Values.storage.name }}
          nfs:
            server: {{ .Values.storage.server }}
            path: {{ .Values.storage.path }}
        - name: {{ .Values.usb.name }}
          hostPath:
            path: {{ .Values.usb.devicePath }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: {{ .Values.affinity.nodeLabel }}
                  operator: In
                  values:
                    - {{ .Values.affinity.value | quote }}
