apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.prometheus.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.prometheus.ingress.host }}
      http:
        paths:
          - path: {{ .Values.prometheus.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.prometheus.name }}
                port:
                  number: {{ .Values.prometheus.ingress.port }}
    - host: {{ .Values.grafana.ingress.host }}
      http:
        paths:
          - path: {{ .Values.grafana.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-grafana
                port:
                  number: {{ .Values.grafana.ingress.port }}
  tls:
    - hosts:
        - {{ .Values.prometheus.ingress.host }}
        - {{ .Values.grafana.ingress.host }}
      secretName: prometheus-stack-cert
