jehlinet_hosts:
  hosts:
    pve: # PVE host (HP mini PC)
      ansible_host: 10.0.10.4
    holly: # Holly PVE host (NAS)
      ansible_host: 10.0.10.5
    overwatcher: # Frigate on Raspberry Pi 4
      ansible_host: 10.0.10.128
    printer-buddy: # RPi Zero W as a print/scanner server
      ansible_host: 10.0.20.230
  vars:
    ansible_user: jsolon
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

jehlinet_vms:
  hosts:
    librarian:
      ansible_host: 10.0.40.100
    omv:
      ansible_host: 10.0.40.201
    kube-captain:
      ansible_host: 10.0.40.102
  vars:
    ansible_user: jsolon
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

alpine_hosts:
  hosts:
    # VM that runs avahi-reflect
    reflector:
      ansible_host: 10.0.10.165
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: false
