apiVersion: v1
kind: Namespace
metadata:
  name: homelab-services
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: adminer
  namespace: homelab-services
spec:
  repo: https://ddx32.github.io/homelab
  chart: adminer
  targetNamespace: homelab-services
  version: 0.1.1
  valuesContent: |-
    host: adminer.jehli.net
    ingressClassName: cloudflare-tunnel
    image:
      tag: 5.3.0
