apiVersion: v1
kind: Namespace
metadata:
  name: media-stack
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: deluge
  namespace: media-stack
spec:
  repo: https://ddx32.github.io/homelab
  chart: deluge
  targetNamespace: media-stack
  version: 0.1.3
  valuesContent: |-
    version: 2.2.0
    nfs:
      server: 10.0.40.201
      paths:
        config: /export/ssd-data/deluge/config
        downloads: /export/media-library
    ingress:
      host: deluge.jehli.net
    ingressClassName: cloudflare-tunnel
