apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: esphome-config-pv
  namespace: homeassistant
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: /export/ssd-data/esphome/config
    server: omv.cdglan.org
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: esphome
  namespace: homeassistant
spec:
  repo: https://ddx32.github.io/homelab
  chart: esphome
  targetNamespace: homeassistant
  version: 0.1.3
  valuesContent: |-
    imageTag: 2025.7
    host: esphome.jehli.net
    ingressClassName: cloudflare-tunnel
    volumeName: esphome-config-pv
