apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-pv
  namespace: homeassistant
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /export/ssd-data/homebridge
    server: omv.cdglan.org
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homebridge
  namespace: homeassistant
spec:
  repo: https://ddx32.github.io/homelab
  chart: homebridge
  targetNamespace: homeassistant
  version: 0.1.2
  valuesContent: |-
    image:
      tag: 2024-01-08
    env:
      TZ: Europe/Prague
    ingress:
      hosts:
        - homebridge.cdglan.org
    volumeName: homebridge-pv
