apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  repo: https://ddx32.github.io/homelab
  chart: homeassistant
  targetNamespace: homeassistant
  version: 0.1.11
  valuesContent: |-
    image:
      tag: 2025.9.4
    host: ha.jehli.net
    ingressClassName: cloudflare-tunnel
    storage:
      server: omv.cdglan.org
      name: ha-storage
      path: /export/ssd-data/homeassistant
      mountPath: /config
