apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  repo: https://jellyfin.github.io/jellyfin-helm
  chart: jellyfin
  targetNamespace: jellyfin
  version: 2.3.0
  valuesContent: |-
    image:
      tag: 10.10.7
    jellyfin:
      enableDLNA: true
    deploymentStrategy:
      type: Recreate
    ingress:
      enabled: true
      hosts:
        - host: jellyfin.jehli.net
          paths:
            - path: /
              pathType: ImplementationSpecific
      className: cloudflare-tunnel
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-pvc
      media:
        enabled: true
        existingClaim: jellyfin-media-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: /export/ssd-data/jellyfin/config
    server: omv.cdglan.org
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  nfs:
    path: /export/media-library
    server: omv.cdglan.org
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: jellyfin-config-pv
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  volumeName: jellyfin-media-pv
  storageClassName: nfs
   