apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  version: 56.2.1
  valuesContent: |-
    fullnameOverride: kube-prometheus-stack
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - prometheus.cdglan.org
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.cdglan.org
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - grafana.cdglan.org
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.cdglan.org
    alertmanager:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - alertmanager.cdglan.org
        tls:
          - secretName: alertmanager-tls
            hosts:
            - alertmanager.cdglan.org
