apiVersion: v1
kind: Namespace
metadata:
  name: navidrome
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: navidrome
  namespace: navidrome
spec:
  repo: https://ddx32.github.io/homelab
  chart: navidrome
  targetNamespace: navidrome
  version: 0.1.3
  valuesContent: |-
    version: latest
    nfs:
      server: omv.cdglan.org
      paths:
        data: /export/ssd-data/navidrome/data
        music: /export/media-library
    ingress:
      host: psotify.jehli.net
    ingressClassName: cloudflare-tunnel
    env:
      ND_MUSICFOLDER: /music/music/lib
    envFrom:
      - secretRef:
          name: navidrome-lastfm
