apiVersion: v1
kind: Namespace
metadata:
  name: homelab-services
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx-proxy
  namespace: homelab-services
spec:
  repo: https://ddx32.github.io/homelab
  chart: nginx-proxy
  targetNamespace: homelab-services
  version: 0.1.3
  valuesContent: |-
    targets:
      - name: openmediavault
        enabled: true
        host: 10.0.40.201
        port: 80
        path: /
        ingress:
          host: nas.jehli.net
          path: /
          port: 9062

      - name: dobby-robot
        enabled: true
        host: 10.0.20.251
        port: 80
        path: /
        ingress:
          host: dobby.jehli.net
          path: /
          port: 9061

    global:
      ingressClassName: cloudflare-tunnel
