apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: nginx-ingress-controller
  targetNamespace: nginx-ingress
