apiVersion: v1
kind: Namespace
metadata:
  name: media-stack
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sonarr
  namespace: media-stack
spec:
  repo: https://ddx32.github.io/homelab
  chart: sonarr
  targetNamespace: media-stack
  version: 0.1.0
  valuesContent: |-
    nfs:
      server: omv.cdglan.org
      paths:
        config: /export/ssd-data/sonarr/config
        media: /export/media-library
    ingress:
      host: sonarr.jehli.net
    ingressClassName: cloudflare-tunnel
