---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        ports:
        {{- range .Values.ports }}
          - containerPort: {{ .port }}
        {{- end }}
        volumeMounts:
          - name: {{ .Values.name }}-config
            mountPath: /mosquitto/config
      volumes:
        - name: {{ .Values.name }}-config
          configMap:
            name: {{ .Values.name }}-configmap
            defaultMode: 0700
      securityContext:
        fsGroup: 1883
        runAsUser: 1883
